---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rast3245/public_html/vits/vits/
    - git pull origin production
    - /bin/cp -R vits/. $DEPLOYPATH
    - cd $DEPLOYPATH && php artisan config:clear && php artisan cache:clear && php artisan view:clear
